# 服务启动端口
server:
  port: 18081

# mysql 数据库连接配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///tanhua?characterEncoding=utf8
    username: root
    password: root
  data:
    mongodb:
      uri: mongodb://192.168.183.66:27017/tanhua

# dubbo、zookeeper相关配置
dubbo:
  application:
    name: tanhua-dubbo-service
  registry:
    address: zookeeper://192.168.183.66:2181
  protocol:
    name: dubbo
    port: 20881
  scan:
    base-packages: com.tanhua.dubbo.api
# MybatisPlus配置
mybatis-plus:
  global-config:
    db-config:
      table-prefix: tb_
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
