server:
  port: 18082
spring:
  data:
    mongodb:
      uri: mongodb://192.168.183.66:27017/tanhua
dubbo:
  application:
    name: tanhua-recommend
  registry:
    address: zookeeper://192.168.183.66:2181
rocketmq:
  name-server: 192.168.183.66:9876
  producer:
    send-message-timeout: 10000